apiVersion: v1
kind: Service
metadata:
  name: stream-v3-observer
  namespace: stream-v3
  labels:
    app.kubernetes.io/name: stream-v3
    app.kubernetes.io/component: observer
spec:
  type: NodePort
  selector:
    app.kubernetes.io/name: stream-v3
    app.kubernetes.io/component: observer
  ports:
    - name: metrics
      port: 9108
      targetPort: metrics
      nodePort: 30108
