apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../v3-reports
patches:
  - target:
      group: batch
      version: v1
      kind: CronJob
      name: stream-v3-stream1090-report
      namespace: stream-v3
    patch: |-
      - op: replace
        path: /spec/suspend
        value: false
  - target:
      group: batch
      version: v1
      kind: CronJob
      name: stream-v3-upstream-report
      namespace: stream-v3
    patch: |-
      - op: replace
        path: /spec/suspend
        value: false
  - target:
      group: batch
      version: v1
      kind: CronJob
      name: stream-v3-youtube-api-cost-open-day
      namespace: stream-v3
    patch: |-
      - op: replace
        path: /spec/suspend
        value: false
  - target:
      group: batch
      version: v1
      kind: CronJob
      name: stream-v3-youtube-api-cost-closed-day
      namespace: stream-v3
    patch: |-
      - op: replace
        path: /spec/suspend
        value: false
