from __future__ import annotations

try:
    from ..youtube_monitor import stats_writer
    from ..youtube_watchdog_config import ENFORCE_RESTART
except ImportError:
    from youtube_monitor import stats_writer
    from youtube_watchdog_config import ENFORCE_RESTART


def build_status_payload(
    *,
    status: str,
    healthy: bool,
    fail_count: int,
    degraded_public_count: int,
    video_id: str,
    live_url: str,
    search_reason: str,
    watch_reason: str,
    api_reason: str,
    api_live_state: str,
    stream_active: bool,
    ffmpeg_pid: int,
    ffmpeg_uptime_sec: int,
    ingest_connected: bool,
    ingest_connection: str,
    local_ok: bool,
    oauth_ok: bool,
    api_ok: bool,
    availability_ok: bool,
    public_ok: bool,
    health_source: str,
    legacy_healthy: bool,
    oauth,
    incident_stage: str,
    incident_reason: str,
    failure_kind: str,
    action: str,
    watch_page_verdict: str = "",
    failure_subkind: str = "",
    force_live_on_upcoming_once_enabled: bool = False,
    force_live_triggered: bool = False,
    force_live_reason: str = "",
    oauth_checked_ts_utc: str = "",
    data_api_checked_ts_utc: str = "",
    api_cost_burn_rate_active: bool = False,
    api_cost_burn_rate_reason: str = "",
    api_cost_projected_units_per_day: int = 0,
    api_cost_threshold_units_per_day: int = 0,
    evidence_state: str = "",
    evidence_reason: str = "",
    evidence_action: str = "",
    evidence_blocked_by: tuple[str, ...] = (),
) -> dict:
    return stats_writer.build_status_payload(
        status=status,
        healthy=healthy,
        fail_count=fail_count,
        degraded_public_count=degraded_public_count,
        video_id=video_id,
        live_url=live_url,
        search_reason=search_reason,
        watch_reason=watch_reason,
        watch_page_verdict=watch_page_verdict,
        api_reason=api_reason,
        api_live_state=api_live_state,
        stream_active=stream_active,
        ffmpeg_pid=ffmpeg_pid,
        ffmpeg_uptime_sec=ffmpeg_uptime_sec,
        ingest_connected=ingest_connected,
        ingest_connection=ingest_connection,
        local_ok=local_ok,
        oauth_ok=oauth_ok,
        api_ok=api_ok,
        availability_ok=availability_ok,
        public_ok=public_ok,
        health_source=health_source,
        legacy_healthy=legacy_healthy,
        oauth=oauth,
        incident_stage=incident_stage,
        incident_reason=incident_reason,
        failure_kind=failure_kind,
        action=action,
        enforce_restart=ENFORCE_RESTART,
        failure_subkind=failure_subkind,
        force_live_on_upcoming_once_enabled=force_live_on_upcoming_once_enabled,
        force_live_triggered=force_live_triggered,
        force_live_reason=force_live_reason,
        oauth_checked_ts_utc=oauth_checked_ts_utc,
        data_api_checked_ts_utc=data_api_checked_ts_utc,
        api_cost_burn_rate_active=api_cost_burn_rate_active,
        api_cost_burn_rate_reason=api_cost_burn_rate_reason,
        api_cost_projected_units_per_day=api_cost_projected_units_per_day,
        api_cost_threshold_units_per_day=api_cost_threshold_units_per_day,
        evidence_state=evidence_state,
        evidence_reason=evidence_reason,
        evidence_action=evidence_action,
        evidence_blocked_by=evidence_blocked_by,
    )
