apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: stream-v3-state
  namespace: stream-v3
  labels:
    app.kubernetes.io/name: stream-v3
    app.kubernetes.io/component: runtime
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 20Gi
