apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - youtube-api-cost-open-day-cronjob.yaml
  - youtube-api-cost-closed-day-cronjob.yaml
  - stream1090-report-cronjob.yaml
  - upstream-report-cronjob.yaml
