apiVersion: v1
kind: Secret
metadata:
  name: stream-v3-recovery-token
  namespace: stream-v3
  annotations:
    kubernetes.io/service-account.name: stream-v3-recovery
type: kubernetes.io/service-account-token
