apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: stream-monitoring-v4-retain
  labels:
    app.kubernetes.io/part-of: stream-monitoring-v4
provisioner: rancher.io/local-path
reclaimPolicy: Retain
volumeBindingMode: WaitForFirstConsumer
allowVolumeExpansion: false
