apiVersion: v1
kind: Secret
metadata:
  name: stream-v3-secrets
  namespace: stream-v3
type: Opaque
stringData:
  STREAM_KEY: replace-with-youtube-stream-key
  YTW_API_KEY: replace-with-youtube-data-api-key
  YTW_OAUTH_CLIENT_ID: replace-with-oauth-client-id
  YTW_OAUTH_CLIENT_SECRET: replace-with-oauth-client-secret
  YTW_OAUTH_REFRESH_TOKEN: replace-with-oauth-refresh-token
  STREAM_NOTIFY_DISCORD_WEBHOOK_URL: CHANGE_ME_NOTIFICATION_ENDPOINT
