from __future__ import annotations

import os
from dataclasses import dataclass
from pathlib import Path


def env(name: str, default: str = "") -> str:
    return os.environ.get(name, default).strip()


def int_env(name: str, default: int) -> int:
    raw = env(name, str(default))
    try:
        return int(raw)
    except ValueError:
        return default


SCRIPT_PATH = Path(__file__).resolve()
BASE_DIR = SCRIPT_PATH.parents[2]
_STATE_BASE_DIR_RAW = env("STREAM_RUNTIME_STATE_DIR", "")
if _STATE_BASE_DIR_RAW:
    STATE_BASE_DIR = Path(_STATE_BASE_DIR_RAW).expanduser()
    STATE_BASE_DIR_TEXT = STATE_BASE_DIR.as_posix()
else:
    STATE_BASE_DIR = (BASE_DIR / ".state" / "adsb-streamnew-v2").resolve()
    STATE_BASE_DIR_TEXT = str(STATE_BASE_DIR)

_LOG_BASE_DIR_RAW = env("STREAM_RUNTIME_LOG_DIR", "")
if _LOG_BASE_DIR_RAW:
    LOG_BASE_DIR = Path(_LOG_BASE_DIR_RAW).expanduser()
    LOG_BASE_DIR_TEXT = LOG_BASE_DIR.as_posix()
else:
    LOG_BASE_DIR = STATE_BASE_DIR / "logs"
    LOG_BASE_DIR_TEXT = f"{STATE_BASE_DIR_TEXT}/logs"


def state_path_text(*parts: str) -> str:
    return "/".join((STATE_BASE_DIR_TEXT, *parts))


def log_path_text(*parts: str) -> str:
    return "/".join((LOG_BASE_DIR_TEXT, *parts))

LIVE_URL = env("YTW_LIVE_URL", "")
API_KEY = env("YTW_API_KEY", "")
VIDEO_ID = env("YTW_VIDEO_ID", "")
CHANNEL_ID = env("YTW_CHANNEL_ID", "")
CHANNEL_LIVE_URL = env("YTW_CHANNEL_LIVE_URL", "")
STREAM_SERVICE = env("YTW_STREAM_SERVICE", "adsb-streamnew-youtube-stream.service")
MAX_FAILS = max(1, int_env("YTW_MAX_FAILS", 3))
TIMEOUT_SEC = max(3, int_env("YTW_TIMEOUT_SEC", 8))
STARTUP_GRACE_SEC = max(0, int_env("YTW_STARTUP_GRACE_SEC", 30))
STATE_FILE = env("YTW_STATE_FILE", state_path_text("youtube_watchdog_state.json"))
LOG_FILE = env("YTW_LOG_FILE", log_path_text("youtube_watchdog.jsonl"))
API_CALL_LOG_FILE = env("YTW_API_CALL_LOG_FILE", log_path_text("youtube_api_calls.jsonl"))
OK_LOG_EVERY_SEC = max(0, int_env("YTW_OK_LOG_EVERY_SEC", 300))
STATS_FILE = env("YTW_STATS_FILE", state_path_text("youtube_watchdog_stats.json"))
EVIDENCE_LEDGER_FILE = env("YTW_EVIDENCE_LEDGER_FILE", state_path_text("youtube_evidence_ledger.json"))
OK_HEARTBEAT_FILE = env("YTW_OK_HEARTBEAT_FILE", state_path_text("youtube_watchdog_ok_heartbeat_state.json"))
VIDEO_RESOLVER_STATE_FILE = env(
    "YTW_VIDEO_RESOLVER_STATE_FILE",
    state_path_text("youtube_video_id_resolver_state.json"),
)
ENFORCE_RESTART = env("YTW_ENFORCE_RESTART", "0") == "1"
API_SEARCH_INTERVAL_SEC = max(30, int_env("YTW_API_SEARCH_INTERVAL_SEC", 300))
RESTART_COOLDOWN_SEC = max(60, int_env("YTW_RESTART_COOLDOWN_SEC", 180))
MIN_RESTART_UPTIME_SEC = max(0, int_env("YTW_MIN_RESTART_UPTIME_SEC", 120))
RECOVERING_GRACE_SEC = max(0, int_env("YTW_RECOVERING_GRACE_SEC", 60))
RESTART_BUDGET_HOURLY = max(1, int_env("YTW_RESTART_BUDGET_HOURLY", 3))
RESTART_BUDGET_DAILY = max(1, int_env("YTW_RESTART_BUDGET_DAILY", 12))
RESTART_BUDGET_RELEASE_RECONFIRM_SEC = max(0, int_env("YTW_RESTART_BUDGET_RELEASE_RECONFIRM_SEC", 300))
RESTART_BUDGET_EMERGENCY_OVERRIDE_SEC = max(0, int_env("YTW_RESTART_BUDGET_EMERGENCY_OVERRIDE_SEC", 90))
EVIDENCE_DATA_API_TTL_SEC = max(5, int_env("YTW_EVIDENCE_DATA_API_TTL_SEC", 60))
EVIDENCE_OAUTH_TTL_SEC = max(5, int_env("YTW_EVIDENCE_OAUTH_TTL_SEC", 60))
EVIDENCE_WATCH_TTL_SEC = max(5, int_env("YTW_EVIDENCE_WATCH_TTL_SEC", 60))
EVIDENCE_RESOLVER_TTL_SEC = max(5, int_env("YTW_EVIDENCE_RESOLVER_TTL_SEC", 150))
EVIDENCE_INGEST_TTL_SEC = max(1, int_env("YTW_EVIDENCE_INGEST_TTL_SEC", 15))
EVIDENCE_API_COST_TTL_SEC = max(5, int_env("YTW_EVIDENCE_API_COST_TTL_SEC", 120))
PUBLIC_LIVE_PROBE_ENABLE = env("YTW_PUBLIC_LIVE_PROBE_ENABLE", "1") == "1"
PUBLIC_LIVE_PROBE_TIMEOUT_SEC = max(3, int_env("YTW_PUBLIC_LIVE_PROBE_TIMEOUT_SEC", 10))
UNHEALTHY_API_SEARCH_INTERVAL_SEC = max(30, int_env("YTW_UNHEALTHY_API_SEARCH_INTERVAL_SEC", 60))
VIDEO_RESOLVER_NORMAL_INTERVAL_SEC = max(5, int_env("YTW_VIDEO_RESOLVER_NORMAL_INTERVAL_SEC", 45))
VIDEO_RESOLVER_UNHEALTHY_INTERVAL_SEC = max(1, int_env("YTW_VIDEO_RESOLVER_UNHEALTHY_INTERVAL_SEC", 5))
VIDEO_RESOLVER_MAX_AGE_SEC = max(5, int_env("YTW_VIDEO_RESOLVER_MAX_AGE_SEC", 120))
VIDEO_RESOLVER_FAST_ENTER_STREAK = max(1, int_env("YTW_VIDEO_RESOLVER_FAST_ENTER_STREAK", 2))
VIDEO_RESOLVER_FAST_EXIT_STREAK = max(1, int_env("YTW_VIDEO_RESOLVER_FAST_EXIT_STREAK", 3))
VIDEO_RESOLVER_SEARCH_MIN_INTERVAL_SEC = max(1, int_env("YTW_VIDEO_RESOLVER_SEARCH_MIN_INTERVAL_SEC", 5))
VIDEO_RESOLVER_FAST_SEARCH_WINDOW_SEC = max(30, int_env("YTW_VIDEO_RESOLVER_FAST_SEARCH_WINDOW_SEC", 180))
URL_PRESERVATION_WINDOW_SEC = max(0, int_env("YTW_URL_PRESERVATION_WINDOW_SEC", 180))
VIDEO_RESOLVER_FAST_SEARCH_MAX_CALLS = max(1, int_env("YTW_VIDEO_RESOLVER_FAST_SEARCH_MAX_CALLS", 36))
VIDEO_RESOLVER_REQUIRE_INGEST_FOR_SEARCH = env("YTW_VIDEO_RESOLVER_REQUIRE_INGEST_FOR_SEARCH", "1") == "1"
VIDEO_RESOLVER_INGEST_READY_MEMORY_SEC = max(
    0,
    int_env("YTW_VIDEO_RESOLVER_INGEST_READY_MEMORY_SEC", 30),
)
VIDEO_RESOLVER_FAST_HTTP_TIMEOUT_SEC = max(1, int_env("YTW_VIDEO_RESOLVER_FAST_HTTP_TIMEOUT_SEC", 2))
VIDEO_RESOLVER_FAST_REMOTE_PROBE = env("YTW_VIDEO_RESOLVER_FAST_REMOTE_PROBE", "0") == "1"
VIDEO_RESOLVER_REFRESH_WATCHDOG_STATS_FAST_MODE = (
    env("YTW_VIDEO_RESOLVER_REFRESH_WATCHDOG_STATS_FAST_MODE", "0") == "1"
)
VIDEO_RESOLVER_REMOTE_ENDED_CONFIRM_SEC = max(
    0,
    int_env("YTW_VIDEO_RESOLVER_REMOTE_ENDED_CONFIRM_SEC", 15),
)
VIDEO_ID_CONFIGURED_FALLBACK_BOOT_SEC = max(
    0,
    int_env("YTW_VIDEO_ID_CONFIGURED_FALLBACK_BOOT_SEC", 120),
)
SKIP_RESTART_IF_INGEST_CONNECTED = env("YTW_SKIP_RESTART_IF_INGEST_CONNECTED", "1") == "1"
INGEST_TCP_PORT = max(1, int_env("YTW_INGEST_TCP_PORT", 1935))
INGEST_TCP_PORTS_RAW = env("YTW_INGEST_TCP_PORTS", "")
OAUTH_ENABLE = env("YTW_OAUTH_ENABLE", "0") == "1"
OAUTH_SHADOW_MODE = env("YTW_OAUTH_SHADOW_MODE", "1") == "1"
OAUTH_CLIENT_ID = env("YTW_OAUTH_CLIENT_ID", "")
OAUTH_CLIENT_SECRET = env("YTW_OAUTH_CLIENT_SECRET", "")
OAUTH_REFRESH_TOKEN = env("YTW_OAUTH_REFRESH_TOKEN", "")
OAUTH_TOKEN_URL = env("YTW_OAUTH_TOKEN_URL", "https://oauth2.googleapis.com/token")
OAUTH_TIMEOUT_SEC = max(3, int_env("YTW_OAUTH_TIMEOUT_SEC", 8))
OAUTH_MIN_TOKEN_TTL_SEC = max(30, int_env("YTW_OAUTH_MIN_TOKEN_TTL_SEC", 90))
OAUTH_PROBE_MIN_INTERVAL_SEC = max(0, int_env("YTW_OAUTH_PROBE_MIN_INTERVAL_SEC", 120))
OAUTH_TOKEN_STATE_FILE = env("YTW_OAUTH_TOKEN_STATE_FILE", state_path_text("youtube_oauth_token_state.json"))
OAUTH_REQUIRE_CHANNEL_MATCH = env("YTW_OAUTH_REQUIRE_CHANNEL_MATCH", "1") == "1"
QUOTA_STATE_FILE = env("YTW_QUOTA_STATE_FILE", state_path_text("youtube_quota_state.json"))
QUOTA_EXHAUSTED_COOLDOWN_SEC = max(60, int_env("YTW_QUOTA_EXHAUSTED_COOLDOWN_SEC", 21600))
QUOTA_RESET_MARGIN_SEC = max(0, int_env("YTW_QUOTA_RESET_MARGIN_SEC", 300))
DATA_API_CHECK_MIN_INTERVAL_SEC = max(0, int_env("YTW_DATA_API_CHECK_MIN_INTERVAL_SEC", 120))
RESOLVER_REUSE_WATCHDOG_OAUTH_SEC = max(0, int_env("YTW_RESOLVER_REUSE_WATCHDOG_OAUTH_SEC", 180))
RESOLVER_REUSE_WATCHDOG_DATA_API_SEC = max(0, int_env("YTW_RESOLVER_REUSE_WATCHDOG_DATA_API_SEC", 180))
API_COST_BURN_RATE_ENABLE = env("YTW_API_COST_BURN_RATE_ENABLE", "1") == "1"
API_COST_BURN_RATE_LATEST_FILE = env(
    "YTW_API_COST_BURN_RATE_LATEST_FILE",
    state_path_text("reports", "youtube_api_cost", "open_day_latest.json"),
)
API_COST_BURN_RATE_THRESHOLD_UNITS_PER_DAY = max(
    0,
    int_env("YTW_API_COST_BURN_RATE_THRESHOLD_UNITS_PER_DAY", 9000),
)
API_COST_BURN_RATE_MIN_ELAPSED_SEC = max(
    60,
    int_env("YTW_API_COST_BURN_RATE_MIN_ELAPSED_SEC", 1800),
)
API_COST_BURN_RATE_MAX_AGE_SEC = max(
    30,
    int_env("YTW_API_COST_BURN_RATE_MAX_AGE_SEC", 1800),
)
API_COST_BURN_RATE_CLOCK_SKEW_ALLOW_SEC = max(
    0,
    int_env("YTW_API_COST_BURN_RATE_CLOCK_SKEW_ALLOW_SEC", 120),
)
API_COST_BURN_RATE_FAIL_CLOSED = env("YTW_API_COST_BURN_RATE_FAIL_CLOSED", "1") == "1"
API_COST_BURN_RATE_OAUTH_MIN_INTERVAL_SEC = max(
    0,
    int_env("YTW_API_COST_BURN_RATE_OAUTH_MIN_INTERVAL_SEC", 600),
)
API_COST_BURN_RATE_DATA_API_MIN_INTERVAL_SEC = max(
    0,
    int_env("YTW_API_COST_BURN_RATE_DATA_API_MIN_INTERVAL_SEC", 600),
)
OAUTH_STREAM_STATUS_REQUIRED = env("YTW_OAUTH_STREAM_STATUS_REQUIRED", "1") == "1"
RESTART_REASON_FILE = env("RESTART_REASON_FILE", state_path_text("restart_reason.json"))
RESTART_FAILURE_BACKOFF_SEC = max(0, int_env("YTW_RESTART_FAILURE_BACKOFF_SEC", 300))
FORCE_LIVE_ON_UPCOMING_ONCE = env("YTW_FORCE_LIVE_ON_UPCOMING_ONCE", "0") == "1"
FORCE_LIVE_AUTO_RECOVERY = env("YTW_FORCE_LIVE_AUTO_RECOVERY", "0") == "1"
FORCE_LIVE_ALLOW_REPLACEMENT_BROADCAST = env("YTW_FORCE_LIVE_ALLOW_REPLACEMENT_BROADCAST", "0") == "1"
FORCE_LIVE_MIN_FAILS = max(1, int_env("YTW_FORCE_LIVE_MIN_FAILS", MAX_FAILS))
FORCE_LIVE_REQUIRE_INGEST = env("YTW_FORCE_LIVE_REQUIRE_INGEST", "1") == "1"
FORCE_LIVE_TARGET_STATUS = env("YTW_FORCE_LIVE_TARGET_STATUS", "live").lower() or "live"
FORCE_LIVE_BROADCAST_ID = env("YTW_FORCE_LIVE_BROADCAST_ID", "")
FORCE_LIVE_STATE_FILE = env("YTW_FORCE_LIVE_STATE_FILE", state_path_text("youtube_force_live_state.json"))
FORCE_LIVE_REQUIRE_OAUTH_STREAM_ACTIVE = env("YTW_FORCE_LIVE_REQUIRE_OAUTH_STREAM_ACTIVE", "1") == "1"
FORCE_LIVE_CATEGORY_ID = env("YTW_FORCE_LIVE_CATEGORY_ID", "")
FORCE_LIVE_REPLACEMENT_ENABLE_AUTO_STOP = env("YTW_FORCE_LIVE_REPLACEMENT_ENABLE_AUTO_STOP", "0") == "1"
FORCE_LIVE_REPLACEMENT_ENABLE_AUTO_START = env("YTW_FORCE_LIVE_REPLACEMENT_ENABLE_AUTO_START", "1") == "1"
FORCE_LIVE_MIN_STREAM_UPTIME_SEC = max(0, int_env("YTW_FORCE_LIVE_MIN_STREAM_UPTIME_SEC", 45))
FORCE_LIVE_REPLACEMENT_MIN_ELAPSED_SEC = max(
    0,
    int_env("YTW_FORCE_LIVE_REPLACEMENT_MIN_ELAPSED_SEC", URL_PRESERVATION_WINDOW_SEC),
)
FORCE_LIVE_BACKOFF_BASE_SEC = max(60, int_env("YTW_FORCE_LIVE_BACKOFF_BASE_SEC", 900))
FORCE_LIVE_BACKOFF_MAX_SEC = max(FORCE_LIVE_BACKOFF_BASE_SEC, int_env("YTW_FORCE_LIVE_BACKOFF_MAX_SEC", 21600))
FORCE_LIVE_BACKOFF_MAX_EXP = max(0, int_env("YTW_FORCE_LIVE_BACKOFF_MAX_EXP", 6))
FORCE_LIVE_MAX_ATTEMPTS_PER_DAY = max(1, int_env("YTW_FORCE_LIVE_MAX_ATTEMPTS_PER_DAY", 24))
FORCE_LIVE_SUCCESS_COOLDOWN_SEC = max(60, int_env("YTW_FORCE_LIVE_SUCCESS_COOLDOWN_SEC", 1800))
INCIDENT_CONFIRM_FAILS = max(1, int_env("YTW_INCIDENT_CONFIRM_FAILS", 2))


@dataclass
class OAuthProbeResult:
    enabled: bool
    configured: bool
    probe_ok: bool
    healthy: bool
    reason: str
    mode: str
    life_cycle_status: str = ""
    broadcast_id: str = ""
    video_id: str = ""
    channel_id: str = ""
    bound_stream_id: str = ""
    stream_status: str = ""
    stream_health_status: str = ""
    stream_health_issues: int = 0
    stream_status_required: bool = False
    remote_checked: bool = False
    enable_auto_start: bool | None = None
    enable_auto_stop: bool | None = None
    monitor_stream_enabled: bool | None = None


@dataclass
class DataApiCheckResult:
    checked: bool
    api_ok: bool
    live_state: str
    reason: str
