from __future__ import annotations

from .classification import (
    build_artist_slot_counts,
    build_others_artist_counts,
    classification_priority as _classification_priority,
    classify_genre,
    classify_track,
    infer_slot_from_artists,
    source_priority as _source_priority,
)
from .constants import (
    APPLIED_OVERRIDE_CONFIDENCE,
    CLASSIFIED_TIME_SLOTS,
    DURATION_PROBE_PATTERNS,
    GENRE_TO_SLOT,
    MAX_TRACK_SEC,
    NON_ROTATION_PATTERNS,
    SKIP_REASONS,
    SOURCE_DIRS,
    TIME_SLOTS,
)
from .duration import ffprobe_duration_sec, is_long_track, read_audio, should_probe_duration, track_duration_sec
from .library import (
    build_library_candidates,
    initial_source_counts as _initial_source_counts,
    link_track,
    organize_library,
    reset_target_dirs,
    selected_library_items,
)
from .overrides import (
    _confirmed,
    _iter_exclude_patterns,
    _override_entry,
    _valid_slot,
    apply_confirmed_manual_override,
    load_classification_overrides,
    manual_override_for_track,
)
from .report import build_others_report, default_others_suggestion as _default_others_suggestion, format_others_report
from .text import (
    artist_tokens,
    display_track_title,
    genre_from_filename,
    genre_from_title_tag,
    normalize_genre,
    normalize_track_title,
    normalized_phrase_in_text,
)

__all__ = [
    "APPLIED_OVERRIDE_CONFIDENCE",
    "CLASSIFIED_TIME_SLOTS",
    "DURATION_PROBE_PATTERNS",
    "GENRE_TO_SLOT",
    "MAX_TRACK_SEC",
    "NON_ROTATION_PATTERNS",
    "SKIP_REASONS",
    "SOURCE_DIRS",
    "TIME_SLOTS",
    "_classification_priority",
    "_confirmed",
    "_default_others_suggestion",
    "_initial_source_counts",
    "_iter_exclude_patterns",
    "_override_entry",
    "_source_priority",
    "_valid_slot",
    "apply_confirmed_manual_override",
    "artist_tokens",
    "build_artist_slot_counts",
    "build_library_candidates",
    "build_others_artist_counts",
    "build_others_report",
    "classify_genre",
    "classify_track",
    "display_track_title",
    "ffprobe_duration_sec",
    "format_others_report",
    "genre_from_filename",
    "genre_from_title_tag",
    "infer_slot_from_artists",
    "is_long_track",
    "link_track",
    "load_classification_overrides",
    "manual_override_for_track",
    "normalize_genre",
    "normalize_track_title",
    "normalized_phrase_in_text",
    "organize_library",
    "read_audio",
    "reset_target_dirs",
    "selected_library_items",
    "should_probe_duration",
    "track_duration_sec",
]
