from __future__ import annotations

SOURCE_DIRS = ("major", "minor")
TIME_SLOTS = ("morning", "day", "evening", "night", "others")
CLASSIFIED_TIME_SLOTS = tuple(slot for slot in TIME_SLOTS if slot != "others")
SKIP_REASONS = ("skipped_long", "skipped_duplicate", "skipped_excluded")
MAX_TRACK_SEC = 600.0
APPLIED_OVERRIDE_CONFIDENCE = "confirmed"

NON_ROTATION_PATTERNS = (
    ("behind the scenes", "program asset, not a normal music track"),
    ("thank you", "program asset, not a normal music track"),
    ("twitchcon", "event/live asset, not a normal music track"),
    ("is live", "event/live asset, not a normal music track"),
    ("keeps getting faster", "meme/novelty asset, not a normal music track"),
    ("mashup", "mashup asset; review before putting into normal rotation"),
    ("mix", "mix asset; review before putting into normal rotation"),
    ("10 years of ncs", "anniversary asset; review before normal rotation"),
)

DURATION_PROBE_PATTERNS = (
    "mix",
    "hour",
    "album",
    "best of",
    "subscriber",
    "views",
    "10 year",
    "13 year",
    "track and build",
    "halloween",
    "new years",
)

GENRE_TO_SLOT = {
    "house": "day",
    "melodic house": "morning",
    "progressive house": "morning",
    "electro house": "day",
    "tropical house": "morning",
    "deep house": "night",
    "chill house": "morning",
    "chillstep": "morning",
    "tech house": "day",
    "rally house": "morning",
    "garage house": "day",
    "slap house": "day",
    "speed house": "day",
    "phouse": "day",
    "electronic pop": "day",
    "futurepop": "day",
    "hyperpop": "day",
    "indie dance": "day",
    "future house": "day",
    "dance pop": "day",
    "alternative pop": "day",
    "alternative dance": "day",
    "j pop": "day",
    "pop": "day",
    "alternative": "day",
    "future bounce": "day",
    "breaks": "day",
    "breakbeat": "day",
    "funk": "day",
    "krushfunk": "day",
    "disco": "day",
    "discoplug": "day",
    "latin dance": "day",
    "hip hop": "day",
    "alternative hip hop": "day",
    "electronic rock": "day",
    "alternative rock": "day",
    "drum & bass": "evening",
    "drum and bass": "evening",
    "dnb": "day",
    "liquid dnb": "night",
    "jump up dnb": "evening",
    "trap": "evening",
    "future trap": "evening",
    "phonk": "night",
    "brazilian phonk": "night",
    "phonk version": "night",
    "hardstyle": "evening",
    "happy hardcore": "evening",
    "bass house": "evening",
    "drumstep": "evening",
    "future bass": "evening",
    "color bass": "evening",
    "colourbass": "evening",
    "baile bass": "evening",
    "glitch hop": "evening",
    "hardcore": "evening",
    "dubstep": "evening",
    "uk dubstep": "evening",
    "dubstep female vocal": "evening",
    "bass": "evening",
    "techno": "day",
    "trance": "day",
    "psytrance": "day",
    "future rave": "evening",
    "hype": "evening",
    "chill": "night",
    "melodic dubstep": "night",
    "electronic": "night",
    "electro": "night",
    "electronic female vocal": "night",
    "electronic male vocal": "night",
    "lofi": "night",
    "lo fi hip hop": "night",
    "synthwave": "night",
    "witch house": "night",
    "witch funk": "night",
    "garage": "night",
    "speed garage": "night",
    "complextro": "night",
    "midtempo": "night",
    "mid tempo": "night",
    "midtempo bass": "night",
    "cyberpunk": "night",
    "jersey club": "night",
    "pluggnb": "night",
    "cloud rap": "night",
    "wave": "night",
    "new jazz": "night",
    "chill funk": "night",
}
